import { Platform, StyleSheet } from 'react-native';

export const C = {
  bg: '#F3F5F8', surface: '#FFFFFF', ink: '#101828', muted: '#566076', line: '#D7DDE8',
  accent: '#2343E0', accentInk: '#FFFFFF', accentSoft: '#E6EAFD', ok: '#0E7A4B', okSoft: '#DDF3E8',
  warn: '#8A5200', warnSoft: '#FBEBCF', stop: '#B3261E', stopSoft: '#FBE2E0', hosted: '#EEF0F3',
};
const display = Platform.select({ ios: 'Avenir Next', android: 'sans-serif-condensed', default: "'Bricolage Grotesque', 'Arial Narrow', Arial, sans-serif" });
const mono = Platform.select({ ios: 'Menlo', android: 'monospace', default: 'ui-monospace, Menlo, monospace' });

export const s = StyleSheet.create({
  screen: { flex: 1, backgroundColor: C.bg },
  view: { padding: 16, paddingTop: 10, gap: 12 },
  foot: { padding: 16, paddingTop: 10, gap: 8, borderTopWidth: 1, borderTopColor: C.line, backgroundColor: C.surface },
  h: { fontFamily: display, fontWeight: '700', fontSize: 24, lineHeight: 28, color: C.ink },
  sub: { color: C.muted, fontSize: 14 },
  k: { fontSize: 11, fontWeight: '600', letterSpacing: 1, textTransform: 'uppercase', color: C.muted },
  back: { color: C.accent, fontSize: 14, paddingVertical: 4 },
  btn: { backgroundColor: C.accent, borderRadius: 12, paddingVertical: 14, paddingHorizontal: 16, minHeight: 48, alignItems: 'center', justifyContent: 'center' },
  btnText: { color: C.accentInk, fontWeight: '600', fontSize: 16 },
  ghost: { backgroundColor: 'transparent', borderWidth: 1, borderColor: C.line },
  ghostText: { color: C.ink },
  vault: { backgroundColor: C.accent, borderRadius: 18, padding: 16, gap: 4 },
  vaultAmt: { fontFamily: display, fontWeight: '700', fontSize: 36, color: C.accentInk },
  vaultMeta: { fontSize: 13, color: C.accentInk, opacity: 0.85 },
  rowc: { backgroundColor: C.surface, borderWidth: 1, borderColor: C.line, borderRadius: 14, paddingVertical: 12, paddingHorizontal: 14, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 10 },
  strong: { fontWeight: '600', color: C.ink, fontSize: 15 },
  small: { fontSize: 13, color: C.muted },
  link: { color: C.accent, fontWeight: '600', fontSize: 14 },
  empty: { borderWidth: 1, borderStyle: 'dashed', borderColor: C.line, borderRadius: 14, padding: 16 },
  pill: { alignSelf: 'flex-start', fontSize: 11, fontWeight: '600', letterSpacing: 0.5, textTransform: 'uppercase', paddingVertical: 3, paddingHorizontal: 8, borderRadius: 999, backgroundColor: C.okSoft, color: C.ok, overflow: 'hidden' },
  textarea: { minHeight: 110, borderWidth: 1, borderColor: C.line, borderRadius: 14, padding: 12, backgroundColor: C.surface, color: C.ink, fontSize: 16, textAlignVertical: 'top' },
  opt: { flexDirection: 'row', gap: 12, alignItems: 'flex-start', backgroundColor: C.surface, borderWidth: 1, borderColor: C.line, borderRadius: 14, padding: 12 },
  optOn: { borderColor: C.accent, backgroundColor: C.accentSoft },
  radio: { width: 18, height: 18, borderRadius: 9, borderWidth: 2, borderColor: C.line, marginTop: 2, alignItems: 'center', justifyContent: 'center' },
  radioOn: { borderColor: C.accent },
  radioDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: C.accent },
  nm: { fontWeight: '600', fontSize: 14, lineHeight: 18, color: C.ink },
  pr: { fontWeight: '600', color: C.ink, fontSize: 15 },
  lines: { backgroundColor: C.surface, borderWidth: 1, borderColor: C.line, borderRadius: 14, paddingVertical: 4, paddingHorizontal: 14 },
  line: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 9, borderBottomWidth: 1, borderBottomColor: C.line },
  lineText: { fontSize: 14, color: C.ink },
  lineTotal: { fontSize: 16, fontWeight: '600', color: C.ink },
  track: { height: 10, borderRadius: 999, backgroundColor: C.line, overflow: 'hidden' },
  fill: { height: '100%', borderRadius: 999, backgroundColor: C.ok },
  mrow: { flexDirection: 'row', justifyContent: 'space-between' },
  note: { fontSize: 13, color: C.muted },
  alert: { backgroundColor: C.stopSoft, borderRadius: 12, paddingVertical: 10, paddingHorizontal: 12 },
  alertText: { color: C.stop, fontSize: 14, fontWeight: '500' },
  toast: { backgroundColor: C.warnSoft, borderRadius: 12, paddingVertical: 10, paddingHorizontal: 12 },
  toastText: { color: C.warn, fontSize: 14, fontWeight: '500' },
  doneMark: { width: 64, height: 64, borderRadius: 32, backgroundColor: C.okSoft, alignItems: 'center', justifyContent: 'center', alignSelf: 'center', marginTop: 8 },
  bigval: { fontFamily: display, fontWeight: '700', fontSize: 48, textAlign: 'center', color: C.ink },
  url: { marginHorizontal: 12, marginTop: 8, paddingVertical: 8, paddingHorizontal: 12, borderRadius: 10, backgroundColor: C.surface, borderWidth: 1, borderColor: C.line, fontFamily: mono, fontSize: 12, color: C.muted },
  thumb: { width: 48, height: 48, borderRadius: 8, backgroundColor: C.hosted },
  stepRow: { flexDirection: 'row', gap: 10, alignItems: 'center' },
  stepDot: { width: 16, height: 16, borderRadius: 8, borderWidth: 2, borderColor: C.line },
});
